pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_ACCESS_KEY_PRIVATE')
        AWS_DEFAULT_REGION    = 'us-east-1'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'develop',
                    url: 'https://github.com/kush1306/microservices-platform.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('terraform') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('terraform') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }

        stage('Get EC2 Public IP') {
            steps {
                dir('terraform') {
                    script {
                        env.EC2_IP = sh(
                            script: 'terraform output -raw public_ip',
                            returnStdout: true
                        ).trim()
                    }
                }

                echo "EC2 Public IP: ${env.EC2_IP}"
            }
        }

        stage('SSH into EC2') {
            steps {
                sshagent(['ec2-ss-key']) {
                    sh '''
                        ssh -v -o StrictHostKeyChecking=no \
                        ubuntu@$EC2_IP \
                        "echo SSH_SUCCESS"
                    '''
                }
            }
        }

        stage('Copy Project to EC2') {
            steps {
                sshagent(['ec2-ssh-key']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no \
                        ubuntu@$EC2_IP \
                        "mkdir -p ~/microservices-platform"

                        scp -o StrictHostKeyChecking=no -r \
                        authentication-service \
                        inventory-service \
                        notification-service \
                        order-service \
                        product-service \
                        user-service \
                        docker-compose.yml \
                        ubuntu@$EC2_IP:~/microservices-platform/
                    '''
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                sshagent(['ec2-ssh-key']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no \
                        ubuntu@$EC2_IP \
                        "cd ~/microservices-platform && docker compose build"
                    '''
                }
            }
        }

        stage('Run Containers') {
            steps {
                sshagent(['ec2-ssh-key']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no \
                        ubuntu@$EC2_IP \
                        "cd ~/microservices-platform && docker compose up -d"
                    '''
                }
            }
        }

        stage('Wait for Services') {
            steps {
                sleep 15
            }
        }

        stage('Verify Endpoints') {
            steps {
                sshagent(['ec2-ssh-key']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP "
                            curl -f http://localhost:8000/api/v1/health &&
                            curl -f http://localhost:8001/health &&
                            curl -f http://localhost:8002/health &&
                            curl -f http://localhost:8003/health &&
                            curl -f http://localhost:8004/health &&
                            curl -f http://localhost:8005/health
                        "
                    '''
                }
            }
        }
    }
}
