pipeline {
     agent any 
   stages {
    stage('Checkout'){
        steps{
            git branch: 'develop', url: 'https://github.com/kush1306/microservices-platform.git'
        }
    }
    stage('Build Docker Image'){
        steps{
            sh 'docker compose build'
        }
    }
    stage('Run containers') {
        steps{
            sh 'docker compose up -d'
        }
    }
    stage('Wait for services') {
        steps {
             sh 'sleep 15'
       }
   }
    stage('Verify Endpoints'){
        steps{
            sh 'curl http://localhost:8000/api/v1/health'
            sh 'curl http://localhost:8001/health'
            sh 'curl http://localhost:8002/health'
            sh 'curl http://localhost:8003/health'
            sh 'curl http://localhost:8004/health'
            sh 'curl http://localhost:8005/health'
        }
    }
    stage('Manual check') {
        steps{
            sh 'sleep 120'  
        } 
    }
    stage('Cleanup'){
        steps{
            sh 'docker compose down'
        }
     }
   }
}

